config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :trips, except: :show
  root 'trips#index'

  resources :trips do
    get :autocomplete_trip_place, :on => :collection
    get :autocomplete_trip_car, :on => :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  validates :first_name,
            presence: true
  validates :last_name,
    presence: true

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, flash: { danger: "You are not logged in!" } if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, flash: { success: "Logged in!" }
    else
        # render :new, flash: { danger: "invalid"}
        redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, flash: { success: "Logged out" }
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authorize
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  autocomplete :trip, :place
  autocomplete :trip, :car

  # GET /trips
  # GET /trips.json
  def index
    if params[:userid]
      @trips = Trip.order('trips.depdate DESC').all.paginate(:page => params[:page], per_page: 12).where("creator=#{params[:userid]}")
    else
      @trips = Trip.order('trips.depdate DESC').all.paginate(:page => params[:page], per_page: 12)
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.creator = current_user.id
    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, flash: {success: 'Trip was successfully created.' } }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    if current_user.id == @trip.creator
      respond_to do |format|
        if @trip.update(trip_params)
          format.html { redirect_to @trip, flash: { succes: 'Trip was successfully updated.' } }
          format.json { render :show, status: :ok, location: @trip }
        else
          format.html { render :edit }
          format.json { render json: @trip.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url, flash: { danger: 'You do not have permission'}
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    if current_user.id == @trip.creator
      @trip.destroy
      respond_to do |format|
        format.html { redirect_to trips_url, flash: { success: 'Trip was successfully destroyed.' } }
        format.json { head :no_content }
      end
    else
      redirect_to root_url, flash: { danger: 'You do not have permission'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:depdate, :place, :description, :phone, :capacity, :car)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user
      @users = User.all
    else
      redirect_to root_url, flash: {danger: "You do not have permission"}
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, flash: { success: "User was successfully created."}
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if current_user.id == @user.id
      if @user.update(user_params)
        redirect_to @user, flash: { success: 'User was successfully updated.' }
      else
        render :edit
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user.id == @user.id
      @user.destroy
      redirect_to users_url, flash: { success: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<% if current_user %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/">Trips</a>
       </div>
       <div class="collapse navbar-collapse" id="myNavbar">
         <ul class="nav navbar-nav">
          <li> <%= link_to "Add Trip", new_trip_path %></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li><a href="/trips?userid=<%= current_user.id %>"><%= current_user.to_s %></a></li>
           <li><%= link_to "Log out", logout_path %></li>
         </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trips</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, class: "alert alert-#{key} alert-dismissable fade in") do %>
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <p><%= value %></p>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_for @trip, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :depdate, class: 'control-label col-md-2' %>
    <div class="col-md-10">
        <%= f.date_select :depdate %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :place, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :place, class: 'text_field form-control', :required => true, data: {autocomplete: autocomplete_trip_place_trips_path } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :description, class: 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, class: 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :capacity, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :capacity, class: 'text_field form-control', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :car, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :car, class: 'text_field form-control', :required => true, data: {autocomplete: autocomplete_trip_car_trips_path } %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  trips_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/trips/edit.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/trips/index.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<!-- <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:depdate) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:car) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody> -->


  <div class="flex-container">
    <% @trips.each do |trip| %>
      <div class="trip panel panel-info">
        <div class="panel-heading"
            <h3 class="panel-title"><%= trip.place %></h3>
        </div>
        <div class="panel-body">
          Departure date:<b> <%= trip.depdate %></b>
        </div>
        <div class="panel-footer">
          <%= link_to trip_path(trip), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <% if trip.creator == current_user.id %>
            <%= link_to edit_trip_path(trip), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
              <%= glyph 'pencil' %>
            <%- end -%>
            <%= link_to trip_path(trip), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
            <%- end -%>
          <% end %>
        </div>
                  <!-- <tr>
                     <td><%= trip.id %></td>
                      <td><%= trip.depdate %></td>
                      <td><%= trip.place %></td>
                      <td><%= trip.description %></td>
                      <td><%= trip.phone %></td>
                      <td><%= trip.capacity %></td>
                      <td><%= trip.car %></td>
                    <td><%=l trip.created_at, format: :long %></td>
                    <td> -->


      </div>
    <% end %>
  </div>
  <!-- </tbody>
</table> -->

<div class="paginator">
  <%= will_paginate @trips, renderer: BootstrapPagination::Rails, previous_label: "Newer", next_label: "Older", inner_window: 0, outer_window: 0 %>
</div>

app/views/trips/new.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/trips/show.html.erb
<%- model_class = Trip -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="trip panel panel-info">
  <div class="panel-heading"
      <h3 class="panel-title"><%= @trip.place %></h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
        <dt><strong><%= model_class.human_attribute_name(:description) %></strong></dt>
        <dd><%= @trip.description %></dd>
        <dt><strong><%= model_class.human_attribute_name(:phone) %></strong></dt>
        <dd><%= @trip.phone %></dd>
        <dt><strong><%= model_class.human_attribute_name(:capacity) %></strong></dt>
        <dd><%= @trip.capacity %></dd>
        <dt><strong><%= model_class.human_attribute_name(:car) %></strong></dt>
        <dd><%= @trip.car %></dd>
    </dl>
  </div>
  <div class="panel-footer">
    <%= link_to t('.back', default: t("helpers.links.back")),
                trips_path, class: 'btn btn-default'  %>
                <% if @trip.creator == current_user.id %>
    <%= link_to t('.edit', default: t("helpers.links.edit")),
                edit_trip_path(@trip), class: 'btn btn-default' %>
    <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                trip_path(@trip),
                method: 'delete',
                data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                class: 'btn btn-danger' %>
                <% end %>
              </div>
              <div>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'form-signin'}  do |f| %>
  <h2>Sign up</h2>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</strong>

      <% user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

    <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name', required: true %>

    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name', required: true %>

    <%= f.text_field :email, class: 'form-control', placeholder: 'Email', required: true %>

    <%= f.password_field :password, class: 'form-control', placeholder: 'Password', required: true %>

    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password', required: true %>


  <button class="btn btn-lg btn-primary btn-block" type="submit">Signup</button>
  <%= link_to 'Login', login_path %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>